import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:uuid/uuid.dart';

import 'measure.dart';
final _supabase = Supabase.instance.client;
const uuid = Uuid();
List<Measure> dummyDataLastWeek = [
  Measure.base(
    id: uuid.v1(),
    userId: _supabase.auth.currentUser!.id,
    createdAt: DateTime.now().subtract(const Duration(days: 6)),
    respiratoryRate: 35,
    temperature: 43,
    heartRate: 23,
    oxygenSaturation: 88,
  ),
  Measure.base(
    id: uuid.v1(),
    userId: _supabase.auth.currentUser!.id,
    createdAt: DateTime.now().subtract(const Duration(days: 6)),
    respiratoryRate: 32,
    temperature: 41,
    heartRate: 33,
    oxygenSaturation: 85,
  ),
  Measure.base(
    id: uuid.v1(),
    userId: _supabase.auth.currentUser!.id,
    createdAt: DateTime.now().subtract(const Duration(days: 6)),
    respiratoryRate: 36,
    temperature: 41,
    heartRate: 33,
    oxygenSaturation: 85,
  ),
  Measure.base(
    id: uuid.v1(),
    userId: _supabase.auth.currentUser!.id,
    createdAt: DateTime.now().subtract(const Duration(days: 6)),
    respiratoryRate: 44,
    temperature: 42,
    heartRate: 34,
    oxygenSaturation: 88,
  ),
  Measure.base(
    id: uuid.v1(),
    userId: _supabase.auth.currentUser!.id,
    createdAt: DateTime.now().subtract(const Duration(days: 5)),
    respiratoryRate: 9.4,
    temperature: 28.7,
    heartRate: 91.2,
    oxygenSaturation: 97.8,
  ),
  Measure.base(
    id: uuid.v1(),
    userId: _supabase.auth.currentUser!.id,
    createdAt: DateTime.now().subtract(const Duration(days: 5)),
    respiratoryRate: 6.1,
    temperature: 24.5,
    heartRate: 108.9,
    oxygenSaturation: 94.3,
  ),
  Measure.base(
    id: uuid.v1(),
    userId: _supabase.auth.currentUser!.id,
    createdAt: DateTime.now().subtract(const Duration(days: 5)),
    respiratoryRate: 11.8,
    temperature: 21.3,
    heartRate: 82.4,
    oxygenSaturation: 98.1,
  ),
  Measure.base(
    id: uuid.v1(),
    userId: _supabase.auth.currentUser!.id,
    createdAt: DateTime.now().subtract(const Duration(days: 5)),
    respiratoryRate: 8.5,
    temperature: 30.9,
    heartRate: 123.7,
    oxygenSaturation: 92.7,
  ),
  Measure.base(
    id: uuid.v1(),
    userId: _supabase.auth.currentUser!.id,
    createdAt: DateTime.now().subtract(const Duration(days: 4)),
    respiratoryRate: 13.2,
    temperature: 26.4,
    heartRate: 96.7,
    oxygenSaturation: 96.5,
  ),
  Measure.base(
    id: uuid.v1(),
    userId: _supabase.auth.currentUser!.id,
    createdAt: DateTime.now().subtract(const Duration(days: 4)),
    respiratoryRate: 4.7,
    temperature: 20.8,
    heartRate: 111.6,
    oxygenSaturation: 91.5,
  ),
  Measure.base(
    id: uuid.v1(),
    userId: _supabase.auth.currentUser!.id,
    createdAt: DateTime.now().subtract(const Duration(days: 4)),
    respiratoryRate: 10.9,
    temperature: 18.2,
    heartRate: 72.9,
    oxygenSaturation: 99.7,
  ),
  Measure.base(
    id: uuid.v1(),
    userId: _supabase.auth.currentUser!.id,
    createdAt: DateTime.now().subtract(const Duration(days: 4)),
    respiratoryRate: 6.8,
    temperature: 34.2,
    heartRate: 129.0,
    oxygenSaturation: 90.2,
  ),
  Measure.base(
    id: uuid.v1(),
    userId: _supabase.auth.currentUser!.id,
    createdAt: DateTime.now().subtract(const Duration(days: 3)),
    respiratoryRate: 14,
    temperature: 38,
    heartRate: 89.4,
    oxygenSaturation: 97.3,
  ),
  Measure.base(
    id: uuid.v1(),
    userId: _supabase.auth.currentUser!.id,
    createdAt: DateTime.now().subtract(const Duration(days: 3)),
    respiratoryRate: 12,
    temperature: 37,
    heartRate: 104.1,
    oxygenSaturation: 93.8,
  ),
  Measure.base(
    id: uuid.v1(),
    userId: _supabase.auth.currentUser!.id,
    createdAt: DateTime.now().subtract(const Duration(days: 3)),
    respiratoryRate: 11.5,
    temperature: 36,
    heartRate: 95,
    oxygenSaturation: 98.5,
  ),
  Measure.base(
    id: uuid.v1(),
    userId: _supabase.auth.currentUser!.id,
    createdAt: DateTime.now().subtract(const Duration(days: 3)),
    respiratoryRate: 9.2,
    temperature: 38,
    heartRate: 100,
    oxygenSaturation: 94.6,
  ),
  Measure.base(
    id: uuid.v1(),
    userId: _supabase.auth.currentUser!.id,
    createdAt: DateTime.now().subtract(const Duration(days: 2)),
    respiratoryRate: 12.0,
    temperature: 24.1,
    heartRate: 94.8,
    oxygenSaturation: 95.9,
  ),
  Measure.base(
    id: uuid.v1(),
    userId: _supabase.auth.currentUser!.id,
    createdAt: DateTime.now().subtract(const Duration(days: 2)),
    respiratoryRate: 4.3,
    temperature: 19.7,
    heartRate: 107.8,
    oxygenSaturation: 91.2,
  ),
  Measure.base(
    id: uuid.v1(),
    userId: _supabase.auth.currentUser!.id,

    createdAt: DateTime.now().subtract(const Duration(days: 2)),
    respiratoryRate: 9.7,
    temperature: 16.9,
    heartRate: 69.7,
    oxygenSaturation: 99.3,
  ),
  Measure.base(
    id: uuid.v1(),
    userId: _supabase.auth.currentUser!.id,
    createdAt: DateTime.now().subtract(const Duration(days: 2)),
    respiratoryRate: 7.5,
    temperature: 33.5,
    heartRate: 121.4,
    oxygenSaturation: 92.3,
  ),
  Measure.base(
    id: uuid.v1(),
    userId: _supabase.auth.currentUser!.id,
    createdAt: DateTime.now().subtract(const Duration(days: 1)),
    respiratoryRate: 10.3,
    temperature: 22.8,
    heartRate: 88.5,
    oxygenSaturation: 97.1,
  ),
  Measure.base(
    id: uuid.v1(),
    userId: _supabase.auth.currentUser!.id,
    createdAt: DateTime.now().subtract(const Duration(days: 1)),
    respiratoryRate: 5.9,
    temperature: 21.2,
    heartRate: 103.2,
    oxygenSaturation: 93.5,
  ),
  Measure.base(
    id: uuid.v1(),
    userId: _supabase.auth.currentUser!.id,
    createdAt: DateTime.now().subtract(const Duration(days: 1)),
    respiratoryRate: 11.1,
    temperature: 15.8,
    heartRate: 74.5,
    oxygenSaturation: 98.8,
  ),
  Measure.base(
    id: uuid.v1(),
    userId: _supabase.auth.currentUser!.id,
    createdAt: DateTime.now().subtract(const Duration(days: 1)),
    respiratoryRate: 8.8,
    temperature: 32.2,
    heartRate: 113.8,
    oxygenSaturation: 94.9,
  ),
  Measure.base(
    id: uuid.v1(),
    userId: _supabase.auth.currentUser!.id,
    createdAt: DateTime.now(),
    respiratoryRate: 10,
    temperature: 37.2,
    heartRate: 90,
    oxygenSaturation: 96.2,
  ),
  Measure.base(
    id: uuid.v1(),
    userId: _supabase.auth.currentUser!.id,
    createdAt: DateTime.now(),
    respiratoryRate: 11,
    temperature: 36.8,
    heartRate: 88,
    oxygenSaturation: 93.1,
  ),
  Measure.base(
    id: uuid.v1(),
    userId: _supabase.auth.currentUser!.id,
    createdAt: DateTime.now(),
    respiratoryRate: 13,
    temperature: 37.1,
    heartRate: 95,
    oxygenSaturation: 99.6,
  ),
  Measure.base(
    id: uuid.v1(),
    userId: _supabase.auth.currentUser!.id,
    createdAt: DateTime.now(),
    respiratoryRate: 12.2,
    temperature: 37,
    heartRate: 90,
    oxygenSaturation: 92.9,
  ),
];